name: Update Rates via API

on:
  schedule:
    - cron: '10 2 * * *'
  workflow_dispatch:

jobs:
  update-rates:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger API to update rates
        run: |
          curl -X POST https://rate-now.vercel.app/api/rates \
            -H "Content-Type: application/json" \
            -w "\nStatus: %{http_code}\n" \
            --fail
